#!/bin/bash
# script para a criacao de hosts
# para o uso, digite ./criarvhost <usuario> <nomedohost>
# <usuario> -> Usuario no GNU/Linux
# <nomedohost> -> Nome do host a ser adcionado
#
# IMPORTANTE - (Primeira versão escrito by vitoriamario)
#
# Versão atual, 0.1
# Mantenedor: pixies
# Licença: GPL
#
#

#verifica se o parametro nomedovhost foi digitado
if test $# = 0
then
	echo ERRO:: SINTAXE MAL FORMADA:
	echo Utilize ./apagarvhost usuario nomedovhost.org
	exit 1
fi

# apaga as pastas htdocs
cd /home/$1
rm -rf $2


#apaga arquivo de vhost
rm /etc/apache2/vhosts/$2.vhosts

#apagar os arquivos de log
rm /home/$1/log/apache2/$2_error_log
rm /home/$1/log/apache2/$2_access_log

#reiniciar apache
apache2ctl restart

#voltar para o diretorio /aletta/services
cd /opt/bee/services/
