#!/bin/bash
# script para apagar vhosts no padrao de instalação aletta
# para o uso, digite ./apagarrvhost nomedovhost.org
# 
# escrito por vitoria mario
# use este script como achar melhor. permitido a copia e modificacao

#verifica se o parametro nomedovhost foi digitado
if test $# = 0
then
	echo ERRO:: SINTAXE MAL FORMADA:
	echo Utilize ./apagarvhost usuario nomedovhost.org
	exit 1
fi

# apaga as pastas htdocs
cd /home/$1
rm -rf $2


#apaga arquivo de vhost
rm /etc/apache2/vhosts/$2.vhosts

#apagar os arquivos de log
rm /home/$1/log/apache2/$2_error_log
rm /home/$1/log/apache2/$2_access_log

#reiniciar apache
apache2ctl restart

#voltar para o diretorio /aletta/services
cd /opt/bee/services/
